# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- master

pool:
  vmImage: 'ubuntu-18.04'

# variables:
#   - group: 'test-group'

jobs:
- job: MyJob
  displayName: My First Job
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - script: echo $(test)
- job: MyJob1
  displayName: My First Job1
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - script: echo My first job1